spring:
  application:
    name: springboot-kafka-base-01
  kafka:
    bootstrap-servers: localhost:9092

    producer:
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      auto-offset-reset: latest

    listener:
      ack-mode: manual
    template:
      default-topic: test
  data:
    redis:
      port: 6379
      host: 127.0.0.1



